#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
# config/routes.yaml
export_excel:
    path: /utilisateur/export/excel
    controller: App\Controller\UtilisateurController::exportExcel
