# config/services.yaml

parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # This part was already in your config, so you just keep it unchanged
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Tests/'
            - '../src/Kernel.php'

    # The rest of your services configuration
    # ...

    # Your additional service configuration
    App\Service\TranslationService:
        arguments:
            # Your service arguments
