<?php

namespace Container85LX2QZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_0fTG2WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.0fT_g2W' shared service.
     *
     * @return \App\Controller\AuthenticationUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\TypeReclamationController::login()": the $authenticationUtils argument is type-hinted with the non-existent class or interface: "App\\Controller\\AuthenticationUtils". Did you forget to add a use statement?');
    }
}
