<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQECIexH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQECIexH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQECIexH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQECIexH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQECIexH\App_KernelDevDebugContainer([
    'container.build_hash' => 'QECIexH',
    'container.build_id' => 'f5322c15',
    'container.build_time' => 1709143255,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQECIexH');
