<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container85LX2QZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container85LX2QZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container85LX2QZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container85LX2QZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container85LX2QZ\App_KernelDevDebugContainer([
    'container.build_hash' => '85LX2QZ',
    'container.build_id' => 'e2d5bbe8',
    'container.build_time' => 1708467749,
], __DIR__.\DIRECTORY_SEPARATOR.'Container85LX2QZ');
