<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAsExdH9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAsExdH9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAsExdH9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAsExdH9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAsExdH9\App_KernelDevDebugContainer([
    'container.build_hash' => 'AsExdH9',
    'container.build_id' => '3fafa286',
    'container.build_time' => 1709721503,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAsExdH9');
